FROM python:3.11-alpine

RUN apk add --no-cache ffmpeg

COPY requirements.txt /tmp
RUN pip install --upgrade pip \
 && pip install -r /tmp/requirements.txt \
 && rm /tmp/requirements.txt

COPY . /root/gpt4free

WORKDIR /root/gpt4free

CMD ["streamlit", "run", "./gui/streamlit_app.py"]

EXPOSE 8501
